# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnvrgctl < Formula
  desc ""
  homepage "https://github.com/dilerous/cnvrgctl"
  version "0.0.5"

  on_macos do
    url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.5/cnvrgctl_0.0.5_darwin_all.tar.gz"
    sha256 "040e158ddfdfc042e5008de26b8c71bb1852eb4e034b63e8750e71e15564c23c"

    def install
      bin.install "cnvrgctl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.5/cnvrgctl_0.0.5_linux_amd64.tar.gz"
        sha256 "520a7ff8144a731585980571ba22ebe11fc35c54cf07077e7faef9f5664bd442"

        def install
          bin.install "cnvrgctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.5/cnvrgctl_0.0.5_linux_arm64.tar.gz"
        sha256 "a7e5f125917e1ee12aaca552737ba35e197d0b1ef2f7d94a9625812557f0d91d"

        def install
          bin.install "cnvrgctl"
        end
      end
    end
  end
end
