# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnvrgctl < Formula
  desc ""
  homepage "https://github.com/dilerous/cnvrgctl"
  version "0.0.4"

  on_macos do
    url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.4/cnvrgctl_0.0.4_darwin_all.tar.gz"
    sha256 "bad9c93d4329c0cea20c4047d37b94dd2350a66ae40607475899d636cf16599a"

    def install
      bin.install "cnvrgctl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.4/cnvrgctl_0.0.4_linux_amd64.tar.gz"
        sha256 "29b08181e546fb20b4e4deea40a6cc134ccf5a6e1c847daa8f09f8bfe02130ca"

        def install
          bin.install "cnvrgctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dilerous/cnvrgctl/releases/download/v0.0.4/cnvrgctl_0.0.4_linux_arm64.tar.gz"
        sha256 "25e27009a00352423053c6f83d2d039b450a3fd35f797f1c88401d8c53344c26"

        def install
          bin.install "cnvrgctl"
        end
      end
    end
  end
end
